# Generated by Django 3.2.12 on 2022-04-18 07:33

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Sinov_ish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baho',
            name='baho',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='2', max_length=100, no_check_for_status=True),
        ),
    ]
