# Generated by Django 3.2.12 on 2022-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sinov_ish', '0002_alter_baho_baho'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='stipendiya',
            field=models.CharField(blank=True, default='yiqilgan', max_length=100, null=True),
        ),
    ]
