# Generated by Django 3.2.12 on 2022-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sinov_ish', '0003_talaba_stipendiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='stipendiya',
            field=models.CharField(blank=True, default='oladi', max_length=100, null=True),
        ),
    ]
